feat(wormbot): add wormbot and change 1,2 cube minicar, autocar
team-monolith-product/scratch-vm pull request #4
Opened 2024-08-05 06:45 UTC by wooms

웜봇 추가 및 0,1 -> 1,2 / minicar,autocar 변경

### Resolves

_What Github issue does this resolve (please include link)?_

### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

2024-08-05 09:02 UTC, a3626a requested changes
궁금한 점이 있습니다.

로보라이즌에서는 코드 버전 관리를 어떻게 하나요?
예를 들어 이번에 작성해주신 코드가, 로보라이즌에서 보유한 어떤 원본(깃 레포)에서 가져와서 붙여넣으신 것인지,
아니면 이번에 완전히 새로 작성하신 것인지 궁금합니다.

추가로 8일 박람회 이전까지, 이번이 마지막 수정일까요?

2024-08-05 09:02 UTC, a3626a commented on src/extensions/roborisen_g2/index.js
> +            }
큐브 2개 이상 관리하는 경우 0, 1 을 직접 치지 않고 드롭다운으로 선택할 수 있게 경험을 개선한 것이 이번 변경의 일부라고 생각합니다.

이 과정에서 cube 인자의 값이 number -> string으로 변경되었는데요. 혹시 menu를 사용하면 반드시 그 value 값이 string이어야 하는것인가요? value를 number로 설정할 수 있다면 형변환에 대한 코드가 불필요할 것 같습니다.

2024-08-05 23:52 UTC, wooms commented on src/extensions/roborisen_g2/index.js
> +            }
- 코드 버전 관리
일단 제가 이해한대로 답변을 드려보겠습니다
저희 스크래치는 X.X.X 버전 메이저.마이너.버그 이런식으로 관리하고 있고 스크래치의 특정 버전을 가져와서 사용하고 있습니다
스크래치 깃헙을 모니터링하면서 큰 변경사항이 일어날경우 업데이트를 하고 있습니다 

이번 코드는 따로 어떤 코드 버전에서 가져와서 붙여넣은것은 아니고 저희 스크래치에도 블루투스가 연결되는 부분이 없고 모두 Scratch Link로 사용하기 때문에 새롭게 작성했습니다

- 마지막 수정
네 박람회 이전까지 마지막 수정입니다

- Number -> String
말씀하신대로 불필요한 것이 맞습니다
수정을 원하신다면 수정해서 올리겠습니다

다만 보통 저희가 0,1 뿐만 아니라 0,1,All 이런식으로 넣다보니 String이 편하고 통일성이 있어서 그렇게 했습니다

2024-08-06 00:37 UTC, a3626a approved these changes
all 과 같은 사례가 있다면 변경하지 않으셔도 괜찮습니다.

2024-08-06 00:37 UTC, merged